common/urls.py
from django.urls import path
from .import views

app_name='common'

urlpatterns = [
    path('home', views.common_home, name='home'),
    path('', views.common_index,name='index'),

]

parent/urls.py
from django.urls import path
from .import views

app_name='parent'

urlpatterns = [
   
    path('', views.parent_index,name='index'),
    path('chat', views.parent_chat,name='chat'),

]

sms/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls')),
    path('parent/', include('parent.urls')),
    path('student/', include('student.urls')),
    path('teacher/', include('teacher.urls')),
    path('smsadmin/', include('smsadmin.urls')),
]

smsadmin/urls.py
from django.urls import path
from .import views

app_name='smsadmin'

urlpatterns = [
 
    path('', views.smsadmin_index,name='index'),

]

student/urls.py
from django.urls import path
from .import views

app_name='student'

urlpatterns = [
   
    path('', views.student_index,name='index'),
    path('leave', views.student_leave,name='leave'),

]

teacher/urls.py
from django.urls import path
from .import views

app_name='teacher'

urlpatterns = [
 
    path('', views.teacher_index,name='index'),
    path('addmarks', views.teacher_addmarks,name='addmarks'),
    path('addtimetable', views.teacher_addtimetable,name='addtimetable'),
    path('addexamtimetable', views.teacher_addexamtimetable,name='addexamtimetable'),

]

parent/models.py
from django.db import models

# Create your models here.

smsadmin/models.py
from django.db import models

# Create your models here.

student/models.py
from django.db import models

# Create your models here.

teacher/models.py
from django.db import models

# Create your models here.

common/views.py
from django.shortcuts import render


# Create your views here.
def common_home(request):
    return render(request,'commontemp/home.html')
def common_index(request):
    return render(request,'commontemp/index.html')    

parent/views.py
from django.shortcuts import render

# Create your views here.
def parent_index(request):
    return render(request,'parenttemp/index.html')
def parent_chat(request):
    return render(request,'parenttemp/chat.html')    

smsadmin/views.py
from django.shortcuts import render

# Create your views here.
def smsadmin_index(request):
    return render(request,'smsadmintemp/index.html')

student/views.py
from django.shortcuts import render


# Create your views here.
def student_index(request):
    return render(request,'studenttemp/index.html')
def student_leave(request):
    return render(request,'studenttemp/leave.html')    

teacher/views.py
from django.shortcuts import render


# Create your views here.
def teacher_index(request):
    return render(request,'teachtemp/index.html')
def teacher_addmarks(request):
    return render(request,'teachtemp/addmarks.html') 
def teacher_addtimetable(request):
    return render(request,'teachtemp/addtimetable.html')   
def teacher_addexamtimetable(request):
    return render(request,'teachtemp/addexamtimetable.html')     

smsadmin/templates/smsadmintemp/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>School Management System</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <link href="{% static 'style/style.css' %}" rel="stylesheet">
</head>
<body>
    <header>
        <!-- Sidebar -->
        <button class="openbtn" onclick="openNav()">&#9776; </button>
        <nav id="sidebarMenu" class="collapse d-lg-block sidebar collapse bg-lightdark">
          <div class="position-sticky">
            <div class="list-group list-group-flush mx-3 mt-4">
                             
                <i class="fas fa-tachometer-alt fa-fw me-3"></i><img src="{% static 'images/school.png' %}" height="70px" width="120px">
                <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&#9776;</a>
              <a
                href="{% url 'teacher:index' %}" class="list-group-item list-group-item-action py-2 ripple bg-lightdark" aria-current="true">
                <i class="fas fa-tachometer-alt fa-fw me-3"></i><span class="linkactive">Dashboard</span>
              </a>
              <a href="#" class="list-group-item list-group-item-action py-2 ripple disabled" style="background-color: #232e33;">
                <i class="fas fa-chart-area fa-fw "></i><span class="fontcol">Add</span>
              </a>

              <div class="list-group list-group-flush mx-3">
                <a href="{% url 'teacher:addmarks' %}" class="list-group-item bg-lightdark">Teacher</a>
                <a href="{% url 'teacher:addtimetable' %}" class="list-group-item bg-lightdark">Student</a>
                <a href="{% url 'teacher:addexamtimetable' %}" class="list-group-item bg-lightdark">Department</a>
                <a href="{% url 'teacher:addexamtimetable' %}" class="list-group-item bg-lightdark">Subject</a>
                <a href="{% url 'teacher:addexamtimetable' %}" class="list-group-item bg-lightdark">Department</a>
                <a href="{% url 'teacher:addexamtimetable' %}" class="list-group-item bg-lightdark">Year or Class</a>
              </div>
              
              <a href="#" class="list-group-item list-group-item-action py-2 ripple disabled" style="background-color: #232e33;">
                ><i class="fas fa-lock fa-fw"></i><span class="fontcol">View</span></a
              >
              <div class="list-group list-group-flush mx-3">
                <a href="{% url 'teacher:addmarks' %}" class="list-group-item bg-lightdark">Teacher</a>
                <a href="{% url 'teacher:addtimetable' %}" class="list-group-item bg-lightdark">Student</a>
                <a href="{% url 'teacher:addexamtimetable' %}" class="list-group-item bg-lightdark">Department</a>
                <a href="{% url 'teacher:addexamtimetable' %}" class="list-group-item bg-lightdark">Subject</a>
                <a href="{% url 'teacher:addexamtimetable' %}" class="list-group-item bg-lightdark">Department</a>
                <a href="{% url 'teacher:addexamtimetable' %}" class="list-group-item bg-lightdark">Year or Class</a>
                <a href="{% url teacher:addtimetable' %}" class="list-group-item bg-lightdark">Time Table</a>
                <a href="{% url 'teacher:addexamtimetable' %}" class="list-group-item bg-lightdark">Exam Time Table</a>
              </div>
            
              
              <a href="#" class="list-group-item list-group-item-action py-2 ripple disabled" style="background-color: #232e33;">
                <i class="fas fa-chart-pie fa-fw"></i><span class="fontcol">Send Notification</span>
              </a>
              <div class="list-group list-group-flush mx-3">
                <a href="#" class="list-group-item bg-lightdark">Students</a>
                <a href="#" class="list-group-item bg-lightdark">Parents</a>
                <a href="#" class="list-group-item bg-lightdark">Teachers</a>
                
              </div>
              <a href="#" class="list-group-item list-group-item-action py-2 ripple bg-lightdark"
                ><i class="fas fa-chart-bar fa-fw"></i><span class="fontcol">Notification</span></a
              >
                            
              <a href="#" class="list-group-item list-group-item-action py-2 ripple bg-lightdark"
                ><i class="fas fa-calendar fa-fw"></i><span class="fontcol">Calendar</span></a
              >
              
            </div>
          </div>
        </nav>
        <!-- Sidebar -->
      
<!-- navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0 mx-auto">
      <span class="mainhead">School Management System</span>
      <li class="nav-item">
        <a class="nav-link logintxt" href="#">IRFAN</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      
      <button class="btn btn-outline-success my-2 my-sm-0 loginbtn" type="submit">Prof</button>
    </form>
  </div>
</nav>
</header>
    
    <section>
        <div class="container-fluid p6">
            <div class="row ">
                <div class="col-12 col-md-6 col-lg-4 pb-4">

                    <div class="colordiv colblue rounded-2">
                      <span class="fontinhead">180</span>
                      <span class="fontin">Students</span>
                      <img src="{% static 'images/students.png' %}" width="120px" height="110px" class="imgclas">
                    </div>
                </div>
                <div class="col-12 col-md-6 col-lg-4 pb-4">
                    <div class="colordiv colbrown rounded-2">
                      <span class="fontinhead">5 +</span>
                      <span class="fontin"> Subjects</span>
                      <img src="{% static 'images/parents.png' %}" width="120px" height="100px" class="imgclas">
                    </div>  
                </div>
               
                
            
                
                <div class="col-12 col-md-6 col-lg-4">
                    <div class="colordiv colgreen rounded-2">
                      <span class="fontinhead">90</span>
                      <span class="fontin">Parents</span>
                      <img src="{% static 'images/parents.png' %}" width="120px" height="100px" class="imgclas">
                    </div>  
                </div>
                
              </div>
                
            </div>
        </div>
    </section>

    <!-- Bar Diagram Area -->
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-6 col-12 p6">
          <img src="{% static 'images/bar.png' %}" height="400px" width="400px" >
        </div>
        <div class="col-md-6 col-12 p7">
          <img src="{% static 'images/bar.png' %}" height="400px" width="400px">
        </div>
      </div> 
    </div>
    

    <script>
      function openNav() {
    document.getElementById("sidebarMenu").style.width = "250px";
  }
  
  /* Set the width of the sidebar to 0 (hide it) */
  function closeNav() {
    document.getElementById("sidebarMenu").style.width = "0";
  }
  </script>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD" crossorigin="anonymous"></script>
</body>
</html>

teacher/templates/teachtemp/addexamtimetable.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>School Management System</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <link href="{% static 'style/style.css' %}" rel="stylesheet">
</head>
<body>
    <header>
        <!-- Sidebar -->
        <button class="openbtn" onclick="openNav()">&#9776; </button>
        <nav id="sidebarMenu" class="collapse d-lg-block sidebar collapse bg-lightdark">
          <div class="position-sticky">
            <div class="list-group list-group-flush mx-3 mt-4">
                             
                <i class="fas fa-tachometer-alt fa-fw me-3"></i><img src="{% static 'images/school.png' %}" height="70px" width="120px">
                <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&#9776;</a>
              <a
                href="{% url 'teacher:index' %}" class="list-group-item list-group-item-action py-2 ripple bg-lightdark" aria-current="true">
                <i class="fas fa-tachometer-alt fa-fw me-3"></i><span class="linkactive">Dashboard</span>
              </a>
              <a href="#" class="list-group-item list-group-item-action py-2 ripple disabled" style="background-color: #232e33;">
                <i class="fas fa-chart-area fa-fw "></i><span class="fontcol">Add</span>
              </a>

              <div class="list-group list-group-flush mx-3">
                <a href="{% url 'teacher:addmarks' %}" class="list-group-item bg-lightdark">Marks</a>
                <a href="{% url 'teacher:addtimetable' %}" class="list-group-item bg-lightdark">Time Table</a>
                <a href="{% url 'teacher:addexamtimetable' %}" class="list-group-item bg-lightdark">Exam Time Table</a>
              </div>
              
              <a href="#" class="list-group-item list-group-item-action py-2 ripple disabled" style="background-color: #232e33;">
                ><i class="fas fa-lock fa-fw"></i><span class="fontcol">View</span></a
              >
              <div class="list-group list-group-flush mx-3">
                <a href="#" class="list-group-item bg-lightdark">Marks</a>
                <a href="#" class="list-group-item bg-lightdark">Attendance</a>
                <a href="#" class="list-group-item bg-lightdark">Students</a>
                <a href="#" class="list-group-item bg-lightdark">Subjects</a>
              </div>
            
              <a href="#" class="list-group-item list-group-item-action py-2 ripple disabled" style="background-color: #232e33;">
                ><i class="fas fa-chart-line fa-fw"></i><span class="fontcol">Attendance</span></a
              >
              <a href="#" class="list-group-item list-group-item-action py-2 ripple disabled" style="background-color: #232e33;">
                <i class="fas fa-chart-pie fa-fw"></i><span class="fontcol">Send Notification</span>
              </a>
              <div class="list-group list-group-flush mx-3">
                <a href="#" class="list-group-item bg-lightdark">Students</a>
                <a href="#" class="list-group-item bg-lightdark">Parents</a>
                
              </div>
              <a href="#" class="list-group-item list-group-item-action py-2 ripple bg-lightdark"
                ><i class="fas fa-chart-bar fa-fw"></i><span class="fontcol">Notification</span></a
              >
              <a href="#" class="list-group-item list-group-item-action py-2 ripple bg-lightdark"
                ><i class="fas fa-globe fa-fw"></i><span class="fontcol">Leave Application</span></a
              >
              
              <a href="#" class="list-group-item list-group-item-action py-2 ripple bg-lightdark"
                ><i class="fas fa-calendar fa-fw"></i><span class="fontcol">Calendar</span></a
              >
              
            </div>
          </div>
        </nav>
        <!-- Sidebar -->
      
<!-- navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0 mx-auto">
      <span class="mainhead">School Management System</span>
      <li class="nav-item">
        <a class="nav-link logintxt" href="#">IRFAN</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      
      <button class="btn btn-outline-success my-2 my-sm-0 loginbtn" type="submit">Prof</button>
    </form>
  </div>
</nav>
</header>

<section>
    <section class="intro">
        <div class="mask d-flex align-items-center h-100 gradient-custom">
          <div class="container">
            <div class="row justify-content-center">
              <div class="col-12 col-lg-9 col-xl-7">
                <div class="card">
                  <div class="card-body p-4 p-md-5">
                    <h3 class="mb-4 pb-2">Exam Time Table </h3>
      
                    
                    <div class="mb-3">
                        <label for="formFile" class="form-label">Upolad Exam Time Table</label>
                        <input class="form-control" type="file" id="formFile">
                      </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
  
    
    
    

    <script>
      function openNav() {
    document.getElementById("sidebarMenu").style.width = "250px";
  }
  
  /* Set the width of the sidebar to 0 (hide it) */
  function closeNav() {
    document.getElementById("sidebarMenu").style.width = "0";
  }
  </script>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD" crossorigin="anonymous"></script>
</body>
</html>

teacher/templates/teachtemp/addmarks.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>School Management System</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <link href="{% static 'style/style.css' %}" rel="stylesheet">
</head>
<body>
    <header>
        <!-- Sidebar -->
        <button class="openbtn" onclick="openNav()">&#9776; </button>
        <nav id="sidebarMenu" class="collapse d-lg-block sidebar collapse bg-lightdark">
          <div class="position-sticky">
            <div class="list-group list-group-flush mx-3 mt-4">
                             
                <i class="fas fa-tachometer-alt fa-fw me-3"></i><img src="{% static 'images/school.png' %}" height="70px" width="120px">
                <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&#9776;</a>
              <a
                href="{% url 'teacher:index' %}" class="list-group-item list-group-item-action py-2 ripple bg-lightdark" aria-current="true">
                <i class="fas fa-tachometer-alt fa-fw me-3"></i><span class="linkactive">Dashboard</span>
              </a>
              <a href="#" class="list-group-item list-group-item-action py-2 ripple disabled" style="background-color: #232e33;">
                <i class="fas fa-chart-area fa-fw "></i><span class="fontcol">Add</span>
              </a>

              <div class="list-group list-group-flush mx-3">
                <a href="{% url 'teacher:addmarks' %}" class="list-group-item bg-lightdark">Marks</a>
                <a href="{% url 'teacher:addtimetable' %}" class="list-group-item bg-lightdark">Time Table</a>
                <a href="{% url 'teacher:addexamtimetable' %}" class="list-group-item bg-lightdark">Exam Time Table</a>
              </div>
              
              <a href="#" class="list-group-item list-group-item-action py-2 ripple disabled" style="background-color: #232e33;">
                ><i class="fas fa-lock fa-fw"></i><span class="fontcol">View</span></a
              >
              <div class="list-group list-group-flush mx-3">
                <a href="#" class="list-group-item bg-lightdark">Marks</a>
                <a href="#" class="list-group-item bg-lightdark">Attendance</a>
                <a href="#" class="list-group-item bg-lightdark">Students</a>
                <a href="#" class="list-group-item bg-lightdark">Subjects</a>
              </div>
            
              <a href="#" class="list-group-item list-group-item-action py-2 ripple disabled" style="background-color: #232e33;">
                ><i class="fas fa-chart-line fa-fw"></i><span class="fontcol">Attendance</span></a
              >
              <a href="#" class="list-group-item list-group-item-action py-2 ripple disabled" style="background-color: #232e33;">
                <i class="fas fa-chart-pie fa-fw"></i><span class="fontcol">Send Notification</span>
              </a>
              <div class="list-group list-group-flush mx-3">
                <a href="#" class="list-group-item bg-lightdark">Students</a>
                <a href="#" class="list-group-item bg-lightdark">Parents</a>
                
              </div>
              <a href="#" class="list-group-item list-group-item-action py-2 ripple bg-lightdark"
                ><i class="fas fa-chart-bar fa-fw"></i><span class="fontcol">Notification</span></a
              >
              <a href="#" class="list-group-item list-group-item-action py-2 ripple bg-lightdark"
                ><i class="fas fa-globe fa-fw"></i><span class="fontcol">Leave Application</span></a
              >
              
              <a href="#" class="list-group-item list-group-item-action py-2 ripple bg-lightdark"
                ><i class="fas fa-calendar fa-fw"></i><span class="fontcol">Calendar</span></a
              >
              
            </div>
          </div>
        </nav>
        <!-- Sidebar -->
      
<!-- navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0 mx-auto">
      <span class="mainhead">School Management System</span>
      <li class="nav-item">
        <a class="nav-link logintxt" href="#">IRFAN</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      
      <button class="btn btn-outline-success my-2 my-sm-0 loginbtn" type="submit">Prof</button>
    </form>
  </div>
</nav>
</header>

<section>
    <section class="intro">
        <div class="mask d-flex align-items-center h-100 gradient-custom">
          <div class="container">
            <div class="row justify-content-center">
              <div class="col-12 col-lg-9 col-xl-7">
                <div class="card">
                  <div class="card-body p-4 p-md-5">
                    <h3 class="mb-4 pb-2">Add Marks</h3>
      
                    
            <form class="px-md-2">
              <div class="row">
                
                <div class="col-md-6 mb-4 ">
              <select class="select select-md bg-sec rounded-4">
                <option value="1" disabled selected>Select Department</option>
                <option value="2">CS</option>
                <option value="3">BBA</option>
                <option value="4">BCom</option>
              </select></div>
              <div class="col-md-6 mb-4">
              <select class="select select-md bg-sec rounded-4">
                <option value="1" disabled selected>Select Year</option>
                <option value="2">I</option>
                <option value="3">II</option>
                <option value="4">III</option>
              </select>
              
              </div>

              <div class="row">
                
                <div class="col-md-6 mb-4">

                  <select class="select bg-sec rounded-4 select-md">
                    <option value="1" disabled selected>Select Subect</option>
                    <option value="2">Python</option>
                    <option value="3">Flutter</option>
                    <option value="4">Android</option>
                  </select>

                </div>
              </div>


             

              <button type="submit" class="btn bg-lightdark mb-1 text-light btn-big">Submit</button>
              
            </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
  
    
    
    

    <script>
      function openNav() {
    document.getElementById("sidebarMenu").style.width = "250px";
  }
  
  /* Set the width of the sidebar to 0 (hide it) */
  function closeNav() {
    document.getElementById("sidebarMenu").style.width = "0";
  }
  </script>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD" crossorigin="anonymous"></script>
</body>
</html>